# Generated by Django 6.0.4 on 2026-04-24 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('type_commune', models.CharField(choices=[('URBAINE', 'Urbaine'), ('RURALE', 'Rurale')], max_length=10)),
                ('population', models.PositiveIntegerField(default=0)),
                ('surface', models.FloatField(blank=True, help_text='Surface en km²', null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('superficie', models.FloatField(blank=True, help_text='Surface en km²', null=True)),
                ('nb_commune', models.PositiveIntegerField(default=1)),
                ('distance_vers_antsohihy', models.FloatField(help_text='Distance en km')),
                ('description_climat', models.TextField(blank=True)),
                ('meteo_info', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='SOFIA', max_length=30)),
                ('chef_lieu', models.CharField(default='Antsohihy', max_length=30)),
                ('nb_district', models.PositiveIntegerField(default=1)),
                ('meteo_actuelle', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ContenuDynamiqueIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contenu', models.CharField(max_length=100)),
                ('texte', models.TextField()),
                ('derniere_maj', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.commune')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.district')),
            ],
        ),
        migrations.AddField(
            model_name='commune',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='communes', to='appli.district'),
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('historique', models.TextField(blank=True)),
                ('position_geo_url', models.URLField(blank=True, help_text='Lien Google Maps', max_length=500)),
                ('niveau_etudes', models.CharField(help_text="Ex: Jardin d'enfant à Terminale", max_length=255)),
                ('nb_eleves', models.PositiveIntegerField(default=0)),
                ('resultat_examen', models.FloatField(default=0, help_text='Taux de réussite en %')),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appli.commune')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Eglise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('historique', models.TextField(blank=True)),
                ('position_geo_url', models.URLField(blank=True, help_text='Lien Google Maps', max_length=500)),
                ('religion', models.CharField(default='Chrétienne', max_length=100)),
                ('est_legale', models.BooleanField(default=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appli.commune')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('categorie', models.CharField(choices=[('HOTEL', 'Hôtel'), ('RESTO', 'Restaurant'), ('LOISIR', 'Centre de loisir'), ('BOUTIQUE', 'Boutique')], max_length=20)),
                ('etoile', models.PositiveIntegerField(default=0)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appli.commune')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sofia_photos/')),
                ('legende', models.CharField(max_length=200)),
                ('commune', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.commune')),
                ('district', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.district')),
                ('etablissement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appli.etablissement')),
            ],
        ),
        migrations.CreateModel(
            name='Quartier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quartiers', to='appli.commune')),
            ],
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='districts', to='appli.region'),
        ),
        migrations.CreateModel(
            name='SiteCulturel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('proprietaire', models.CharField(blank=True, max_length=150)),
                ('description_ia', models.TextField(help_text="Description générée par l'IA")),
                ('activites_possibles', models.TextField(help_text='Culte, événements, commerce de fruits...')),
                ('fady_associe', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('derniere_verification_ia', models.DateTimeField(auto_now=True)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.commune')),
            ],
        ),
        migrations.CreateModel(
            name='StatistiqueHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('evolution_population', models.IntegerField()),
                ('nb_infrastructures_total', models.IntegerField()),
                ('commentaire_ia', models.TextField()),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appli.district')),
            ],
        ),
        migrations.CreateModel(
            name='Usine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('historique', models.TextField(blank=True)),
                ('position_geo_url', models.URLField(blank=True, help_text='Lien Google Maps', max_length=500)),
                ('produits', models.CharField(max_length=200)),
                ('nb_employes', models.PositiveIntegerField(default=0)),
                ('statut_legal', models.CharField(max_length=100)),
                ('commune', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appli.commune')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
