# Generated by Django 6.0.4 on 2026-09-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='district',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
