# Generated by Django 6.0.4 on 2026-04-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='code_postal',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='chef_lieu',
            field=models.CharField(default='Antsohihy (407)', max_length=30),
        ),
    ]
