# Generated by Django 6.0.4 on 2026-09-28 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appli', '0002_district_latitude_district_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='chef_lieu',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='district',
            name='population',
            field=models.PositiveIntegerField(blank=True, help_text='Projection 2020, INSTAT', null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='distance_vers_antsohihy',
            field=models.FloatField(blank=True, help_text="Distance à vol d'oiseau, en km", null=True),
        ),
    ]
